source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name="registration"),
    path("user/<int:pk>/details/", UserDetailView.as_view(), name="user_detailed_view"),
]

source/api/urls.py
from django.urls import path

from api.views import ModerateStatus, CancelStatus

app_name = 'api'

urlpatterns = [
    path('api/moderate/<int:pk>', ModerateStatus.as_view(), name='moderate_status'),
    path('api/cancel/<int:pk>', CancelStatus.as_view(), name='cancel_status'),
]

source/finalexam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from api.views import ModerateStatus

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.moderator import ModeratorList, AdModeratorUpdate
from webapp.views import AdvertisementListView, AdvertisementCreateView, AdvertisementDetailView, \
    AdvertisementDeleteView, AdvertisementUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', AdvertisementListView.as_view(), name='webapp_list'),
    path('advertisement/create/', AdvertisementCreateView.as_view(), name="advertisement_create"),
    path('advertisement/<int:pk>/detail', AdvertisementDetailView.as_view(), name="advertisement_detail"),
    path('advertisement/<int:pk>/delete', AdvertisementDeleteView.as_view(), name="advertisement_delete"),
    path('advertisement/<int:pk>/update', AdvertisementUpdateView.as_view(), name="advertisement_update"),
    path('advertisement/list', ModeratorList.as_view(), name="moderator_list"),
    path('advertisement/operator/<int:pk>/detail', AdModeratorUpdate.as_view(), name="advertisement_operator_detail"),


]

source/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from phonenumber_field.formfields import PhoneNumberField


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name="profile", on_delete=models.CASCADE, verbose_name='Profile')
    phone_number = PhoneNumberField(region="KG", max_length=13)
    email = models.EmailField(blank=False, null=False, verbose_name="Email")
    first_name = models.CharField(max_length=50, blank=False, null=False, verbose_name="Firstname")
    last_name = models.CharField(max_length=50, blank=False, null=False, verbose_name="Lastname")

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'
        permissions = []

    def __str__(self):
        return f"Profile: {self.user}. {self.id} {self.last_name} {self.first_name}, {self.phone_number} "

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, UsernameField


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=100, required=True, label='Email')

    class Meta(UserCreationForm.Meta):
        fields = ("username", "password1", "password2", "email", "first_name", "last_name")

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        email = cleaned_data.get('email')
        if first_name == "" or last_name == "":
            raise ValidationError('Name, Last Name must be filled')
        else:
            return cleaned_data

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import CreateView, DetailView
from accounts.forms import MyUserCreationForm
from webapp.models import Advertisement


class RegisterView(CreateView):
    model = User
    template_name = "registration.html"
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('project_list_view')
        return next_url


class UserDetailView(DetailView):
    template_name = 'user_detailed_view.html'
    model = User
    context_object_name = 'user_object'
    paginate_by = 10
    paginate_orphans = 0

    def get_context_data(self, **kwargs):
        advertisements = Advertisement.objects.filter(author=self.object.pk)
        if advertisements.filter(Q(status='to_moderate') | Q(status='canceled') | Q(status='published')):
            kwargs["advertisements"] = advertisements
            return super().get_context_data(**kwargs)

source/accounts/templates/login.html
 {% extends 'base.html' %}

 {% block content %}
 <div class="container">
                            <h1>Вход</h1>
    <form method="post" class="text-center ms-auto me-auto w-50">
        {% csrf_token %}
        {% if has_error %}
            <p class="invalid-feedback">Incorrect username or password.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Username:</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Password:</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>
        <button type="submit">Login</button>
    </form>

</div>


 {% endblock %}

source/accounts/templates/registration.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
    <h1>Registration</h1>
    <form method="post">
        {% include "partial/form.html" with button_text="Register" %}
    </form>
{% endblock %}

source/accounts/templates/user_detailed_view.html
{% extends 'base.html' %}

{% block content %}


    <h2>My Profile</h2>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone Number</th>
        </tr>
        </thead>

        <tbody>
        <tr>
            <td>{{ user_object.pk }}</td>
            <td>{{ user_object.first_name }}</td>
            <td>{{ user_object.last_name }}</td>
            <td>{{ user_object.email }}</td>
        </tr>
        </tbody>
    </table>


    <h2>Advertisements</h2>



    <table class="table">
     <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Image</th>
            <th scope="col">Category</th>
            <th scope="col">Author</th>
            <th scope="col">Price</th>
            <th scope="col">Status</th>
            <th scope="col">Date Created</th>

        </tr>
        </thead>
        <tbody>
        {% for ad in advertisements %}
            <tr>
            <th scope="row">{{ ad.pk }}</th>

            {% if ad.image %}
                <td><img class="image" src="{{ ad.image.url }}" height="100" width="100" alt="ad image">
                </td>
            {% else %}
                <td><img class="image" height="100" width="100"
                         src="https://pbs.twimg.com/profile_images/496102814880239616/IDgM95XQ_400x400.png"
                         alt="Block Image"></td>

            {% endif %}


            <td>{{ ad.category }}</td>
            <td>{{ ad.author }}</td>
            <td>{{ ad.price }}</td>
            <td>{{ ad.status }}</td>
            <td>{{ ad.date_created }}</td>
              <td><a class="btn btn-primary btn-sm ps-3 pe-3"
                   href="{% url "webapp:advertisement_detail" ad.pk %}">Detail</a></td>
            <td><a class="btn btn-primary btn-sm ps-3 pe-3"
                   href="{% url "webapp:advertisement_update" ad.pk %}">Update</a></td>

            <td><a class="btn btn-primary btn-sm ps-3 pe-3"
                   href="{% url "webapp:advertisement_delete" ad.pk %}">Delete</a></td>

        {% endfor %}
        </tbody>
    </table>



{% endblock %}