source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name="registration"),
    path("user/<int:pk>/details/", UserDetailView.as_view(), name="user_detailed_view"),
]

source/api/urls.py
from django.urls import path

from api.views import ModerateStatus, CancelStatus

app_name = 'api'

urlpatterns = [
    path('api/moderate/<int:pk>', ModerateStatus.as_view(), name='moderate_status'),
    path('api/cancel/<int:pk>', CancelStatus.as_view(), name='cancel_status'),
]

source/finalexam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from api.views import ModerateStatus

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.moderator import ModeratorList, AdModeratorUpdate
from webapp.views import AdvertisementListView, AdvertisementCreateView, AdvertisementDetailView, \
    AdvertisementDeleteView, AdvertisementUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', AdvertisementListView.as_view(), name='webapp_list'),
    path('advertisement/create/', AdvertisementCreateView.as_view(), name="advertisement_create"),
    path('advertisement/<int:pk>/detail', AdvertisementDetailView.as_view(), name="advertisement_detail"),
    path('advertisement/<int:pk>/delete', AdvertisementDeleteView.as_view(), name="advertisement_delete"),
    path('advertisement/<int:pk>/update', AdvertisementUpdateView.as_view(), name="advertisement_update"),
    path('advertisement/list', ModeratorList.as_view(), name="moderator_list"),
    path('advertisement/operator/<int:pk>/detail', AdModeratorUpdate.as_view(), name="advertisement_operator_detail"),


]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
CHOICES = [('to_moderate', 'To Moderate'), ('published', 'Published'), ('canceled', 'Canceled'), ('deleted', 'Deleted')]


class Advertisement(models.Model):
    category = models.ForeignKey('webapp.Category', null=False, blank=False, on_delete=models.CASCADE, related_name="advertisements", verbose_name="Category")
    image = models.ImageField(upload_to="images/", null=False, blank=False, verbose_name="Image")
    headline = models.CharField(max_length=100, null=False, blank=False, verbose_name="Headline")
    description = models.TextField(max_length=100, null=True, blank=False, verbose_name="Description")
    price = models.DecimalField(null=True, blank=True, max_digits=7, decimal_places=2, verbose_name="Price")
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    date_edited = models.DateTimeField(auto_now_add=True, verbose_name="Date edited")
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="Date published")
    status = models.CharField(default=CHOICES[0][0], choices=CHOICES, max_length=100, null=False, blank=False, verbose_name="Status")
    author = models.ForeignKey("accounts.Profile", null=False, blank=False, on_delete=models.CASCADE, related_name="advertisements", verbose_name="Advertisement")

    def __str__(self):
        return f"{self.pk}. {self.headline} {self.category} {self.date_created}"

    class Meta:
        db_table = "advertisement"
        verbose_name = "Advertisement"
        verbose_name_plural = "Advertisements"


class Category(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name="Name")

    def __str__(self):
        return f"{self.pk}. {self.name}"

    class Meta:
        db_table = "category"
        verbose_name = "Category"
        verbose_name_plural = "Categories"

source/webapp/forms.py
from django import forms

from webapp.models import Advertisement


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ("headline", "image", "description", "category",)


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label='Search')

source/webapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView
from webapp.forms import AdvertisementForm
from webapp.models import Advertisement
from webapp.base import SearchView

User = get_user_model()


class AdvertisementListView(SearchView):
    template_name = 'index.html'
    model = Advertisement
    context_object_name = "advertisments"
    paginate_by = 5
    paginate_orphans = 0
    ordering = ["-date_created"]
    search_fields = ['headline']


class AdvertisementCreateView(LoginRequiredMixin, CreateView):
    model = Advertisement
    form_class = AdvertisementForm
    template_name = "create.html"
    permission_required = "webapp.add_advertisement"
    success_url = reverse_lazy('webapp:webapp_list')

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        return super().form_valid(form)


class AdvertisementDetailView(DetailView):
    template_name = 'detail.html'
    model = Advertisement
    context_object_name = 'advertisement'


class AdvertisementDeleteView(PermissionRequiredMixin, DeleteView):
    model = Advertisement
    template_name = "delete.html"
    context_object_name = 'advertisement'
    permission_required = "webapp.delete_advertisement"
    success_url = reverse_lazy('webapp:webapp_list')

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse('webapp:webapp_list', kwargs={"pk": self.object.pk})


class AdvertisementUpdateView(PermissionRequiredMixin, UpdateView):
    form_class = AdvertisementForm
    template_name = "update.html"
    model = Advertisement
    permission_required = "webapp.change_advertisement"

    def form_valid(self, form):
        form.instance.status = "to_moderate"
        return super().form_valid(form)

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse('webapp:advertisement_detail', kwargs={'pk': self.object.pk})

source/webapp/templates/advertisment_operator_detail.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Image</th>
            <th scope="col">Category</th>
            <th scope="col">Author</th>
            <th scope="col">Date Created</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">{{ advertisement.pk }}</th>

            {% if advertisement.image %}
                <td><img class="image" src="{{ advertisement.image.url }}" height="100" width="100" alt="ad image">
                </td>
            {% else %}
                <td><img class="image" height="100" width="100"
                         src="https://pbs.twimg.com/profile_images/496102814880239616/IDgM95XQ_400x400.png"
                         alt="Block Image"></td>

            {% endif %}


            <td>{{ advertisement.category }}</td>
            <td>{{ advertisement.author }}</td>
            <td>{{ advertisement.date_created }}</td>


            <td><a class="btn btn-primary btn-sm ps-3 pe-3" onclick="Moderate(event)" data-api-url="{% url "api:moderate_status" advertisement.pk %}">To Moderate</a></td>

            <td><a class="btn btn-primary btn-sm ps-3 pe-3" onclick="Cancel(event)" data-api-url="{% url "api:cancel_status" advertisement.pk %}">Cancel</a></td>

    </table>

{% endblock %}

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <title>Tracker</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'webapp:webapp_list' %}">WebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'webapp:advertisement_create' %}">Создание статьи</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'webapp:moderator_list' %}">Страница для модератора</a>
                    </li>

                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:registration' %}">Register</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>

                    {% endif %}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link"#}
{#                           href="{% url "accounts:user_detailed_view" user.profile.id %}">Hello, {{ user.profile.first_name }}!</a>#}
{#                    </li>#}
                </ul>
            </div>
        </div>
    </nav>
</header>


<div class="container">
    {% block content %}



    {% endblock %}
</div>

<script type="text/javascript" src="{% static 'js/index.js' %}"></script>

</body>
</html>

source/webapp/templates/create.html
{% extends 'base.html' %}

{% block title %}Create Advertisement{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
    <h1>Create Article</h1>
    <form method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with button_text="Создать" %}
    </form>

{% endblock %}

source/webapp/templates/delete.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="position-absolute top-50 start-50 translate-middle">
            <div class="">
                <form action="{% url "webapp:advertisement_delete" advertisement.pk %}" method="POST">
                    {% csrf_token %}
                    <h2>Do you really want to delete the gallery {{ gallery.name }}</h2>
                    <input type="submit" class="btn btn-primary btn-sm col-1" value="Да">
                </form>
            </div>


            <div class="pt-2">
                <a class="btn btn-primary btn-sm col-1" href="{% url "webapp:webapp_list" %}">Нет</a>
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/detail.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Image</th>
            <th scope="col">Category</th>
            <th scope="col">Author</th>
            <th scope="col">Date Created</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">{{ advertisement.pk }}</th>

            {% if advertisement.image %}
                <td><img class="image" src="{{ advertisement.image.url }}" height="100" width="100" alt="ad image">
                </td>
            {% else %}
                <td><img class="image" height="100" width="100"
                         src="https://pbs.twimg.com/profile_images/496102814880239616/IDgM95XQ_400x400.png"
                         alt="Block Image"></td>

            {% endif %}


            <td>{{ advertisement.category }}</td>
            <td>{{ advertisement.author }}</td>
            <td>{{ advertisement.date_created }}</td>


            <td><a class="btn btn-primary btn-sm ps-3 pe-3"
                   href="{% url "webapp:advertisement_update" advertisement.pk %}">Update</a></td>

            <td><a class="btn btn-primary btn-sm ps-3 pe-3"
                   href="{% url "webapp:advertisement_delete" advertisement.pk %}">Delete</a></td>

    </table>

{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="search">
        {% include 'partial/simple_search.html' %}
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Image</th>
            <th scope="col">Category</th>
            <th scope="col">Author</th>
            <th scope="col">Price</th>
            <th scope="col">Date Created</th>

        </tr>
        </thead>
        <tbody>
        {% for ad in advertisments %}
            <tr>
            <th scope="row">{{ ad.pk }}</th>

            {% if ad.image %}
                <td><img class="image" src="{{ ad.image.url }}" height="100" width="100" alt="ad image">
                </td>
            {% else %}
                <td><img class="image" height="100" width="100"
                         src="https://pbs.twimg.com/profile_images/496102814880239616/IDgM95XQ_400x400.png"
                         alt="Block Image"></td>

            {% endif %}


            <td>{{ ad.category }}</td>
            <td>{{ ad.author }}</td>
            <td>{{ ad.price }}</td>
            <td>{{ ad.date_created }}</td>
            <td><a class="btn btn-primary btn-sm ps-3 pe-3"
                   href="{% url "webapp:advertisement_detail" ad.pk %}">Detail</a></td>
            <td><a class="btn btn-primary btn-sm ps-3 pe-3"
                   href="{% url "webapp:advertisement_update" ad.pk %}">Update</a></td>

            <td><a class="btn btn-primary btn-sm ps-3 pe-3"
                   href="{% url "webapp:advertisement_delete" ad.pk %}">Delete</a></td>

        {% endfor %}
    </table>









    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% if search %}&search={{ search }}{% endif %}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}{% if query %}&{{ search }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if search %}&search={{ search }}{% endif %}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}{% if search %}&search={{ search }}{% endif %}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
{% endblock %}

source/webapp/templates/moderators_page.html
{% extends 'base.html' %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Image</th>
            <th scope="col">Category</th>
            <th scope="col">Author</th>
            <th scope="col">Price</th>
            <th scope="col">Date Created</th>

        </tr>
        </thead>

    </table>


    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% if search %}&search={{ search }}{% endif %}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}{% if query %}&{{ search }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if search %}&search={{ search }}{% endif %}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}{% if search %}&search={{ search }}{% endif %}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
{% endblock %}

source/webapp/templates/update.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

        <form action="" method="POST">
            {% include "partial/form.html" with button_text="Submit" %}
        </form>

        <div class="pt-1">
            <a class="btn btn-primary btn-sm" href="{% url "webapp:webapp_list" %}">Back to main</a>
        </div>
    </div>

{% endblock %}